# management:
#     info:
#         git:
#             mode: full
#         env:
#             enabled: true
server:
    port: 8081
    servlet:
        context-path: /user-service

spring:
  application:
    name: ms-user
  flyway:
    locations: classpath:db/migration/base/
    baseline-on-migrate: true
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-user
    username: postgres
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        open-in-view: false
  security:
    jwt:
      secret: xxdWXHtgXeXs0vaLSRjrORGDZvuRSoRHEOc43IyiLl6YOOjTW5U11Ae0fRA0vyeAHqOvepKwiHTkB/dLZP+ESw== # base64 secret
      expiration: 43200000 # in milliseconds (12 hours)
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


frontend:
  domain:
    url: http://localhost:3000

app:
  topic:
    otp-request: otp.requested

